- name: Run tasks in parallel
  hosts: all
  connection: local
  tasks:
    - name: Run task 1
      command: task_1_command
      async: 300
      poll: 0

    - name: Run task 2
      command: task_2_command
      async: 300
      poll: 0
