---
- hosts: all
  gather_facts: false
  connection: local

  tasks:
    - name: 1. sleep
      command: "sleep 10"
      
    - name: 2. sleep
      command: "sleep 10"

    - name: 3. sleep
      command: "sleep 10"
