---
- hosts: localhost
  gather_facts: false
  connection: local
  tasks:
    - name: test task
      debug:
        msg: "Success !"
---
- hosts: localhost
  gather_facts: false
  connection: local
  tasks:
    - name: test task
      debug:
        msg: "Success !"
---
- hosts: localhost
  gather_facts: false
  connection: local
  tasks:
    - name: test task
      debug:
        msg: "Success !"
---
- hosts: localhost
  gather_facts: false
  connection: local
  tasks:
    - name: test task
      debug:
        msg: "Success !"
---
- hosts: localhost
  gather_facts: false
  connection: local
  tasks:
    - name: test task
      debug:
        msg: "Success !"
