---
- hosts: all
  gather_facts: false
  connection: local
  tasks:
    - name: test task
      debug:
        msg: "Success !"
- hosts: all
  gather_facts: false
  connection: local
  tasks:
    - name: test task
      debug:
        msg: "Success !"
- hosts: all
  gather_facts: false
  connection: local
  tasks:
    - name: test task
      debug:
        msg: "Success !"
- hosts: all
  gather_facts: false
  connection: local
  tasks:
    - name: test task
      debug:
        msg: "Success !"
- hosts: all
  gather_facts: false
  connection: local
  tasks:
    - name: test task
      debug:
        msg: "Success !"
- hosts: all
  gather_facts: false
  connection: local
  tasks:
    - name: test task
      debug:
        msg: "Success !"
